name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  workflow-name:
    description: 'Name of the workflow file to collect statistics from'
    required: true
  test-file-runtime-file:
    description: 'Name of the file to which to write expected test runtimes for scheduling purposes'
    required: true
  artifact-name-regexp:
    description: 'Regular expression to match artifact names containing actual test runtimes'
    required: true
    default: ''

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: ../src/analyze.js
