name: 'Run busted tests'
description: |
  Run tests as specified in an input file that was previously created by the 'schedule' action.
author: 'Hans Hübner, Kong Inc.'
# Define your inputs here.
inputs:
  tests-to-run-file:
    description:
      'Name of the file containing the tests to run, created by "schedule"
      action'
    required: true
  failed-test-files-file:
    description:
      'Name of the file containing failing tests, will override
      tests-to-run-file if existing and be written with failing tests'
    required: true
  test-file-runtime-file:
    description:
      'Name of the file into which to write actual test runtimes for scheduling
      purposes'
    required: true
  xml-output-folder:
    description:
      'Name of the folder into which to write test results in JUnit XML format'
    required: false
  build-root:
    description: "Path to the build root. This is where the script to source to set up Kong's virtual environment is found"
    required: false
  build-dest-path:
    description: "Path to the build destination. Symlinks will be created in this folder pointing to the contents of `build-root/build_name`"
    required: false

runs:
  using: node20
  main: ../src/runner-action.js
